sudo: required
services:
  - dockerfile

before_install:
  - docker build -t vilastadoori/react-test -f ./client/Dockerfile.dev  ./client

script:
  #- docker run vilastadoori/react-test npm test -- --coverage
  - docker run -e CI=true vilastadoori/react-test npm test

after_success:
  - docker build -t vilastadoori/multi-client ./client
  - docker build -t vilastadoori/multi-ngnix  ./nginx
  - docker build -t vilastadoori/multi-server ./server
  - docker build -t vilastadoori/multi-worker ./worker

# Log in to the docker CLI

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub.
- docker push vilastadoori/multi-client
- docker push vilastadoori/multi-nginx
- docker push vilastadoori/multi-server
- docker push vilastadoori/multi-worker