sudo: required
services:
  - dockerfile

before_install:
  - docker build -t vilastadoori/react-test -f ./client/Dockerfile.dev  ./client

script:
  #- docker run vilastadoori/react-test npm test -- --coverage
  - docker run -e CI=true vilastadoori/react-test npm test

after_success:
  - docker build -t vilastadoori/multi-client ./client
  - docker build -t vilastadoori/multi-ngnix  ./ngnix
  - docker build -t vilastadoori/multi-server ./server
  - docker build -t vilastadoori/multi-worker ./worker